name: "Run pgstac and load STAC data"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Pull pgstac Docker image
        run: docker pull stacutils/pgstac:v0.9.2

      - name: Docker login
        if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
      
      - name: Start pgstac server
        run: |
          docker run -d \
            --name pgstac \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e POSTGRES_DB=postgis \
            -p ${{ vars.DB_PORT || 5439 }}:5432 \
            stacutils/pgstac:v0.9.2

      - name: Wait for pgstac to be ready
        run: |
          for i in {1..30}; do
            docker exec pgstac pg_isready -U postgres && break
            sleep 2
          done

      - name: Install pypgstac
        run: pip install pypgstac

      - name: Load STAC data with pypgstac
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ./scripts/load_stac_data.sh ${{ vars.STAC_DATA_DIR || 'testdata' }}